POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer 

{
    "title" : "26.7, 14:12",
    "author" : "JK Botting",
    "url" : "google.com",
    "likes" : 50,
    "userId" : "66a00da575257a1ca45f502f"
}